image: debian:testing-slim

variables:
  PYTHON: python3.8

before_script:
  - apt update
  - apt install -y $PYTHON

.build-and-test:
  script:
  - apt install -y python3-pip devscripts
  - mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
  - pip3 install .
  - $PYTHON setup.py build sdist bdist
  - apt install -y python3-pytest
  - pytest-3

test:
  extends: .build-and-test

codestyle:
  allow_failure: true
  script:
  - apt install -y pycodestyle
  - pycodestyle
